[versions]
kotlin = "2.4.10"
agp = "9.3.1"
android-compileSdk = "37"
android-minSdk = "24"
android-targetSdk = "37"

androidx-lifecycle = "2.11.0"
androidx-datastore-preference = "1.2.1" # https://developer.android.com/jetpack/androidx/releases/datastore
androidx-navigation-compose = "2.9.2" # https://mvnrepository.com/artifact/org.jetbrains.androidx.navigation/navigation-compose-uikitarm64

compose-multiplatform = "1.11.1" # https://github.com/JetBrains/compose-multiplatform/releases
composeBoM = "2026.06.01" # https://developer.android.com/develop/ui/compose/bom/bom-mapping
composables-core = "1.49.9"

koinBoM = "4.2.2" # https://github.com/InsertKoinIO/koin/releases
compottie = "2.2.4"
confetti-kit = "0.8.0"
material3 = "1.12.0-alpha03"

[libraries]
androidx-datastore-preference = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore-preference" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation-compose" }
compose-ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "compose-multiplatform" }
composables-core = { module = "com.composables:core", version.ref = "composables-core" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBoM" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBoM" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-composeVM = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koinBoM" }
compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }
confetti-kit = { module = "io.github.vinceglb:confettikit", version.ref = "confetti-kit" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }